title: My Tech Blog
description: A blog about technology, programming, and development.
google_analytics: [Your Google Analytics tracking ID]
baseurl: "/my-tech-blog" 
url: "https://alex-rosa.github.io"
author: Alex Rosa
email: alrosatexas@gmail.com
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme 
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _drafts
  - _site