title: My Tech Blog
description: A blog about technology, programming, and development.
baseurl: ""
url: "https://my-tech-blog.github.io"
author: Your Name
email: your.email@example.com
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _posts
  - _drafts
  - _site