title: My Tech Blog
description: A blog about technology, programming, and development.
baseurl: "/my-tech-blog" 
url: "https://alex-rosa.github.io"
author: Alex Rosa
email: alrosatexas@gmail.com
theme: architect
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _drafts
  - _site